[package]
name = "susi"
version = "0.1.0"
authors = ["Niclas Hoyer <niclas@verbugt.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
embedded-hal-mock = { path = '../embedded-hal-mock' }

[dependencies]
embedded-hal = "1.0.0-alpha.4"
embedded-time = "0.10.1"
nb = "1.0.0"

[dev-dependencies]
embedded-hal-mock = "0.8.0"
