[package]
name = "susi"
version = "0.1.0"
authors = ["Niclas Hoyer <niclas@verbugt.de>"]
edition = "2018"

[features]
default = ["std"]
std = []

[patch.crates-io]
embedded-hal-mock = { path = '../embedded-hal-mock' }

[dependencies]
embedded-hal = "1.0.0-alpha.4"
embedded-time = "0.10"
nb = "1.0"
num-derive = "0.3"

[dependencies.num-traits]
version = "0.2"
default-features = false

[dev-dependencies]
embedded-hal-mock = "0.8"
